### ISSUE TITLE
SafeFileApiNativeMethods.IpcfEncryptFileStream Invalid pointer HRESULT: 0x80004003

### ISSUE THREAD

**Issue by robladbrook** [Azure-Samples/Azure-Information-Protection-Samples#1]
Hi, I'm trying to test the code locally. I can run SafeFileApiNativeMethods.IpcfEncryptFile without issue, but whenever I try to run SafeFileApiNativeMethods.IpcfEncryptFileStream it gives me an error of "Invalid pointer".

I'm just using MemoryStream based Streams. I've attached the RMS trace.

Could you please let me know if you have any ideas what could be causing the Invalid pointer?

[trace.txt](https://github.com/Azure-Samples/active-directory-dotnet-rms/files/88121/trace.txt)

[code.cs.txt](https://github.com/Azure-Samples/active-directory-dotnet-rms/files/88130/code.cs.txt)

Thanks

**Comment by kkanakas** [comment]
Hello @robladbrook ,
               I know it has been a while, but have you figured out the answer and addressed the issue ?
