### ISSUE TITLE
IpcfGetSerializedLicenseFromFile does not recognize a DNF email message file as an RMS protected document

### ISSUE THREAD

**Issue by jdonoghue28** [Azure-Samples/Azure-Information-Protection-Samples#26]
When trying to gather the license properties on a .msg file that is protected with RMS, the method throws the following error:

Exception calling "IpcfGetSerializedLicenseFromFile" with "1" argument(s): "The application cannot open
this file as it is not encrypted by the Rights Management service.  HRESULT: 0x80041001"

**Comment by jktarun** [comment]
What is solution of this. I'm facing same problem, and not getting how to fix it?

**Comment by jdonoghue28** [comment]
This was the response from microsoft support.  It can be done with custom code.  the sample code alone from Github won't support it.  Good luck.

•	Symptom: When using the RmsDocumentInspector sample code from GitHub and processing a protected message (.msg) file the following error occurs. Exception calling "IpcfGetSerializedLicenseFromFile" with "1" argument(s): "The application cannot open this file as it is not encrypted by the Rights Management service.  HRESULT: 0x80041001"
•	Cause: None of the samples from GitHub support this.
•	Resolution: It can be done, just not with the sample code.
•	More Information: The .msg file is a compressed file. It needs to be decompressed and the file streams parsed. The sample code is not written to handle that.
