### ISSUE TITLE
Track is not working properly with AzureIP Test

### ISSUE THREAD

**Issue by vignesh7021** [Azure-Samples/Azure-Information-Protection-Samples#27]
I am using the 'AzureIP Test' code sample provided in GitHub(https://github.com/Azure-Samples/Azure-Information-Protection-Samples/tree/master/AzureIP_Test) using which I am able to protect the documents using Azure template and AdHoc policy approach. But, If I try to apply Track or Revoke on this protected document(protected using AzureIP Test), using Azure Information Protection Client,  then, in the site https://track.azurerms.com , under 'shared by' column of my protected document, instead of email id of the owner I see an email id in the format  AppPrincipalId@LicensingExtranetDistributionPointUrl(till rms.ap.aadrm.com). Because of this I am not able to apply Track and revoke on the document which is protected using 'AzureIP Test' application.

If the document is protected using Azure information Protection then Track and Revoke is working fine on it because shared column in https://track.azurerms.com site displaying proper email id of the owner.

So please tell me why Track and Revoke not working for documents protected using 'AzureIP Test' application and what needs to be done to make it working. 

Also could you please add safe native method for IpcfEncryptFileWithMetadata so that this application can be directly used for Tracking as well.

**Comment by kkanakas** [comment]
Document tracking with the service application is not supported. Hence the error message.
