### ISSUE TITLE
Not clear on how it is protecting the file from blob storage

### ISSUE THREAD

**Issue by prashantbhojani** [Azure-Samples/Azure-Information-Protection-Samples#3]
Not clear on how it is protecting the file from blob storage. Can you please explain.
I have few questions on this.
1. How the file is protected ?
2. Where can i set permissions?
3. How to open the file, once it is uploaded to blob storage?

**Comment by kkanakas** [comment]
Hi @prashantbhojani ,
               Sorry about delayed response.  Please look at the WorkerRole.cs  code and within that section please review the following piece of code. This is running on the worker VM and looking at the files on associated blob storage that worker VM is monitoring

{
                                    RMS.RmsContent rmsContent = new RMS.RmsContent(sourceStream, sinkStream);
                                    rmsContent.RmsTemplateId = publishJob.TemplateId;
                                    rmsContent.OriginalFileNameWithExtension = publishJob.OriginalFileName;
                                    RMS.RmsContentPublisher rmsContentPublisher = RMS.RmsContentPublisher.Create(sp.TenantId, sp.AppId, sp.Key);
                                    rmsContentPublisher.PublishContent(rmsContent);

```
                                publishJob.PublishedFileName = rmsContent.PublishedFileNameWithExtension;
                                sinkStream.Flush();
                                sinkStream.Seek(0, SeekOrigin.Begin);

                                //published file is uploaded to blob storage.
                                //Note: This sample code doesn't manage lifetime of this original and published file blob
                                //Actual code must manage the lifetime as appropriate
                                CloudBlockBlob destFileBlob = DataModel.StorageFactory.Instance.IpcAzureAppFileBlobContainer.GetBlockBlobReference(publishJob.PublishedFileBlobRef);
                                using (CloudBlobStream blobStream = destFileBlob.OpenWrite())
```
