### ISSUE TITLE
File is not able to make IRM enabled using IpcfEncryptFileStream()

### ISSUE THREAD

**Issue by dips365** [Azure-Samples/Azure-Information-Protection-Samples#31]
Hello,

I am trying to do create a IRM protected file using the method SafeFileApiNativeMethods.IpcfEncryptFileStream().
I have written a code as below.

> Collection<TemplateInfo>templates = SafeNativeMethods.IpcGetTemplateList(
                    connectionInfo: conn,
                    forceDownload: false,
                    suppressUI: false,
                    offline: false,
                    hasUserConsent: false,
                    parentWindow: IntPtr.Zero,
                    cultureInfo: null); 
                    Console.WriteLine("Loaded Templates {0}", templates.Count);
                var template = templates[1];
               Stream connStream = File.OpenRead(filepath);
               Stream connOutputStream = new MemoryStream();
 var handle = SafeNativeMethods.IpcCreateLicenseFromTemplateId(template.TemplateId);
string outputFilePath = SafeFileApiNativeMethods.IpcfEncryptFileStream(connStream, filepath, handle, SafeFileApiNativeMethods.EncryptFlags.IPCF_EF_FLAG_KEY_NO_PERSIST_DISK,ref connOutputStream);

This will return the IRM enabled stream in variable conOutputStream.

But when i am save retrurn stream in file it will write junk characters and RMS template information in XML strings.

Code to write the stream in file as below.

> var f = new FileStream("C://test1.docx", FileMode.Create, FileAccess.Write);
                  connOutputStream.CopyTo(f);
                  f.Dispose();
                  connOutputStream.Close();

Is it necessary to write the stream to the file ? as when i am using the ipcfEncryptFile() file is encrypted successfully but i want t o encrypt it using IpcfEncryptFileStream() method?

How can i make file to IRM Protected file (.Docx) using method IpcfEncryptFileStream()?

Is it correct way to write the file from the IRM Returned stream from the RMS method?

Thanks 
Dipen Shah

**Comment by kkanakas** [comment]
why are you targeting the FileStream for a Office file ? What  are you trying to accomplish using file stream with an office file ?

**Comment by kkanakas** [comment]
Did you look at the documentation for the function 
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/msipc/ipcfencryptfilestream
